# Copyright 2020-2021 Hewlett Packard Enterprise Development LP
# Dockerfile for image which holds the CSM barebones image (squashfs) and Kiwi recipe
FROM arti.dev.cray.com/csm-docker-stable-local/cray-ims-load-artifacts:@ims_load_artifacts_image_tag@

# Use for testing/not in pipeline builds
#FROM arti.dev.cray.com/csm-docker-stable-local/cray-ims-load-artifacts:latest

# Copy the IMS import manifest
COPY manifest.yaml /

# Copy the image/recipe files
COPY build/output/*@product_version@* /
